system_ss.add(when: 'CONFIG_MCP23S08', if_true: files('mcp23s08.c'))
system_ss.add(when: 'CONFIG_LED_DEMUX', if_true: files('led_demux.c'))
system_ss.add(when: 'CONFIG_PARALLEL_SRAM', if_true: files('parallel_sram.c'))
system_ss.add(when: 'CONFIG_WS2812', if_true: files('ws2812.c'))
system_ss.add(when: 'CONFIG_ADF4002', if_true: files('adf4002.c'))
system_ss.add(when: 'CONFIG_FM_TRANSMITTER', if_true: files('fm_transmitter.c'))
system_ss.add(when: 'CONFIG_VCD_TRACE', if_true: files('vcd_trace.c'))
